color: yellow
fieldLayouts:
  f963a26a-1ae7-4018-a377-48603315252a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T08:55:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b867f9f3-d490-4405-aea5-c516fde8d060
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-06T08:58:08+00:00'
            elementCondition: null
            fieldUid: c72a3f62-2918-4562-a5dc-f4ce9058d1f4 # Rich Text Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f422b20c-b6e6-4100-8f0a-60b27f99ea7e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5abdd3c8-d6fd-420c-bdfe-42c62db1292c
        userCondition: null
handle: richText
hasTitleField: false
icon: font-case
name: 'Rich Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{entryId}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
