color: null
fieldLayouts:
  90008bdf-d52a-41af-94e2-41b9f7930fff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-06T11:57:06+00:00'
            elementCondition: null
            fieldUid: 6de8ed43-4ef2-41a4-962e-7fdcd2e65031 # Plain Text
            handle: testimonial
            includeInCards: false
            instructions: null
            label: Testimonial
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cdc702e-292c-4770-b3c6-aaafd0b108c0
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-06T11:53:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc390fca-3a19-4f14-84f3-da1447b39cdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-06T11:57:06+00:00'
            elementCondition: null
            fieldUid: 6de8ed43-4ef2-41a4-962e-7fdcd2e65031 # Plain Text
            handle: location
            includeInCards: false
            instructions: null
            label: Location
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51a112c8-8359-465b-883f-593494b546bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e865495-da65-4015-ac3f-3de62af44721
        userCondition: null
handle: testimonials
hasTitleField: true
icon: messages
name: Testimonials
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
