color: null
fieldLayouts:
  8c4021ec-cc4f-436d-acda-8ff1444dc84d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e616e7c-4ece-40db-bca6-1b61e31671ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6de8ed43-4ef2-41a4-962e-7fdcd2e65031 # Plain Text
            handle: linkText
            includeInCards: false
            instructions: null
            label: 'Link Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18b57efa-ec3c-4c15-831e-d0ffff31629a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2bcdf88c-4733-4b12-b3fe-9799c2773aea # URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e220bf8-93e9-48b1-abb6-4d44fc64b3a2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64ff6725-9629-4162-9d7e-55a099b2d722
        userCondition: null
handle: textLink
hasTitleField: false
icon: link
name: 'Text Link'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{linkText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
