dateModified: 1725880856
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - authors
        - link
      type: native
    -
      key: singles
      type: native
    -
      key: 'section:3e394d1a-6745-477e-90a6-d9aea2f71188' # Adventures
      type: native
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:f80f1d9a-9689-4aa1-9688-5bf4e20efc71' # Locations
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - authors
        - link
      type: native
email:
  fromEmail: ryan@craftquest.io
  fromName: 'House Quest'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/local'
    type: craft\fs\Local
    url: '@web/local'
meta:
  __names__:
    2bcdf88c-4733-4b12-b3fe-9799c2773aea: URL # URL
    2fa9c924-e215-49c1-ba08-660b2b04acb5: 'Content Builder' # Content Builder
    3db93919-04b1-4128-975f-f831ed967af0: Homepage # Homepage
    3e394d1a-6745-477e-90a6-d9aea2f71188: Adventures # Adventures
    5ebfdea0-4852-45f6-961c-31de85495858: Adventures # Adventures
    6de8ed43-4ef2-41a4-962e-7fdcd2e65031: 'Plain Text' # Plain Text
    8f8b8035-b0d0-44a9-b3af-681ce34f8cad: 'Text Link' # Text Link
    9bebaaa3-6d87-4c75-afc8-f5f75ab950c4: Images # Images
    10a7e081-e196-46ea-a6c3-6f04496d7de0: About # About
    19eaa83e-07ac-462d-9d31-928fb4fd4cf3: Testimonials # Testimonials
    69d923c0-06ba-468b-be90-9c6885e5e710: Homepage # Homepage
    82e25a63-e6c1-4634-a675-ec8f2e3868ff: FAQs # FAQs
    89e6df1f-af15-42ee-b1ca-95ca80f456c2: 'Content Builder CK' # Content Builder CK
    99d56909-2e5f-46e7-a360-37ef5f53f971: Location # Location
    396f0793-7466-4fc7-8d32-be8328d2369b: About # About
    460a499b-f8f1-4721-9a4f-aec7570042fd: 'Call To Action' # Call To Action
    620caa93-2603-4217-9713-700e82292681: 'Public Schema' # Public Schema
    695adb81-e37d-40c6-91f1-96198a560e1c: 'Content Builder' # Content Builder
    4052097c-4aec-4442-af4c-df0a26b20065: 'Craft 5' # Craft 5
    16080038-b7ee-465a-869e-112483ff46c0: 'Simple Table' # Simple Table
    a62a212f-7b95-4908-8315-df40cc1a5093: 'Text Link' # Text Link
    a5462f8d-6e69-451f-bcbf-9bb200fc174d: Image # Image
    aada7c0a-0401-46f7-bc65-12fc53fb9109: Simple # Simple
    b93f0c37-9d23-4379-a1b7-6b76af1181ab: Stats # Stats
    c72a3f62-2918-4562-a5dc-f4ce9058d1f4: 'Rich Text Content' # Rich Text Content
    ca5e0d18-e144-47cd-946e-047f4febda59: 'Rich Text' # Rich Text
    d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: 'Craft 5' # Craft 5
    ea9b90a7-89ea-48f5-b25f-9c0675e0d876: images # images
    f80f1d9a-9689-4aa1-9688-5bf4e20efc71: Locations # Locations
    f92db1fe-0a5a-4f76-bc5d-867ce8a9b650: Locations # Locations
    fe374ec6-3f0b-4484-84e4-45a29a3a93b7: Testimonials # Testimonials
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: pro
  live: true
  name: 'Craft 5'
  retryDuration: null
  schemaVersion: 5.3.0.2
  timeZone: America/Chicago
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
