defaultPlacement: end
enableVersioning: true
entryTypes:
  - ca5e0d18-e144-47cd-946e-047f4febda59 # Rich Text
handle: faqs
maxAuthors: 1
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: faqs.twig
    uriFormat: faqs
type: single
