defaultPlacement: end
enableVersioning: true
entryTypes:
  - f92db1fe-0a5a-4f76-bc5d-867ce8a9b650 # Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: 1
  uid: 70322d2c-ef03-41bb-8e88-e6cc0804572c
type: structure
