defaultPlacement: end
enableVersioning: true
entryTypes:
  - fe374ec6-3f0b-4484-84e4-45a29a3a93b7 # Testimonials
handle: testimonials
maxAuthors: 1
name: Testimonials
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d9d1ae21-b5ed-442d-bc28-0e3aa8b8c39b: # Craft 5
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
